# Generated by Django 4.0 on 2024-02-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BngJobs',
        ),
        migrations.DeleteModel(
            name='PuneJobs',
        ),
    ]
