# Generated by Django 4.0 on 2024-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_delete_bngjobs_delete_punejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.TextField(),
        ),
    ]
